# Generated by Django 4.1.3 on 2022-12-13 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_profile_followers_profile_timestamp_profile_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.FileField(default='default.jpg', upload_to='image/profile/avatar'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='cover_image',
            field=models.FileField(default='cover.jpg', upload_to='image/profile/cover'),
        ),
    ]
